openapi: 3.0.3
info:
  title: ITA Version2.0 API
  description: ITAv2.0用API
  version: 1.0.0
servers:
- url: /
tags:
- name: Menu Info
  description: メニュー情報の取得
- name: Menu Filter
  description: レコードの取得
- name: Menu Maintenance
  description: レコードの操作（登録/更新/廃止/復活/物理削除）
- name: Menu MaintenanceAll
  description: レコードの一括操作（登録/更新/廃止/復活/物理削除）
- name: Menu Excel
  description: Excelの取得・操作
- name: User Info
  description: ユーザ情報の取得
paths:
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/info/:
    get:
      tags:
      - Menu Info
      description: メニューの基本情報および項目情報を取得する
      operationId: get_menu_info
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_info_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/info/column/:
    get:
      tags:
      - Menu Info
      description: メニューの項目一覧(REST用項目名)を取得する
      operationId: get_column_list
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_info_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/info/pulldown/{column}/:
    get:
      tags:
      - Menu Info
      description: 項目のプルダウン選択用の一覧を取得する
      operationId: get_pulldown_list
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: column
        in: path
        description: REST用項目名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_info_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/filter/:
    get:
      tags:
      - Menu Filter
      description: レコードを全件取得する
      operationId: get_filter
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_filter_controller
    post:
      tags:
      - Menu Filter
      description: 検索条件を指定し、レコードを取得する
      operationId: post_filter
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: 検索条件を設定
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_filter_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/filter/journal/{uuid}:
    get:
      tags:
      - Menu Filter
      description: レコードの履歴を取得する
      operationId: get_journal
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: uuid
        in: path
        description: UUID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_filter_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/maintenance/:
    post:
      tags:
      - Menu Maintenance
      description: レコードを登録する
      operationId: maintenance_register
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/menu_maintenance_body'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_maintenance_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/maintenance/{uuid}:
    patch:
      tags:
      - Menu Maintenance
      description: レコードを更新/廃止/復活する
      operationId: maintenance_update
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: uuid
        in: path
        description: 対象のUUID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: 更新する値を設定。廃止/復活は廃止フラグを更新することで実施。
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_maintenance_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/maintenance/all/:
    post:
      tags:
      - Menu MaintenanceAll
      description: レコードを一括で登録/更新/廃止/復活する
      operationId: maintenance_all
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: 登録/更新/廃止/復活するidとレコードの値を設定
              items:
                $ref: '#/components/schemas/MAINTENANCE_PARAMETERS'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_maintenance_all_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/excel/:
    get:
      tags:
      - Menu Excel
      description: レコードを全件取得する
      operationId: get_excel_filter
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_excel_controller
    post:
      tags:
      - Menu Excel
      description: 検索条件を指定し、レコードを取得する
      operationId: post_excel_filter
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: 検索条件を設定
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_excel_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/menu/{menu}/excel/maintenance:
    post:
      tags:
      - Menu Excel
      description: Excelでレコードを登録/更新/廃止/復活する
      operationId: post_excel_maintenance
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: menu
        in: path
        description: メニュー名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.menu_excel_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/user/:
    get:
      tags:
      - User Info
      description: ユーザの権限情報を取得する
      operationId: get_user_auth
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.user_info_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/user/menus/:
    get:
      tags:
      - User Info
      description: ユーザがアクセス可能なメニューグループ・メニューの一覧を取得する
      operationId: get_user_menus
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.user_info_controller
  /api/{organization_id}/workspaces/{workspace_id}/ita/user/menus/panels/:
    get:
      tags:
      - User Info
      description: メニューグループの画像を取得する
      operationId: get_menu_group_panels
      parameters:
      - name: organization_id
        in: path
        description: OrganizationID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: workspace_id
        in: path
        description: WorkspaceID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_7'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
      x-openapi-router-controller: controllers.user_info_controller
components:
  schemas:
    TABLE:
      type: object
      properties:
        PAGE_NO:
          type: integer
        TD:
          type: object
        TD_IHP:
          type: object
        UNIQUE_VAL:
          type: object
      example:
        TD: {}
        TD_IHP: {}
        PAGE_NO: 0
        UNIQUE_VAL: {}
    COLUMN_INFO:
      type: object
      additionalProperties:
        type: object
        properties:
          column_id:
            type: string
            description: 項目ID
          column_name:
            type: string
            description: 表示用項目名
          column_name_rest:
            type: string
            description: REST用項目名
          column_group_id:
            type: string
            description: カラムグループID
          column_group_name:
            type: string
            description: カラムグループ名
          column_type:
            type: integer
            description: カラムタイプ
          column_disp_seq:
            type: integer
            description: 表示順
          description:
            type: string
            description: 項目説明
          ref_table_name:
            type: string
            description: ID連携テーブル名
          ref_pkey_name:
            type: string
            description: ID連携テーブルPK
          ref_col_name:
            type: string
            description: ID連携項目名
          ref_sort_conditions:
            type: string
            description: ID連携ソート条件
          ref_multi_lang:
            type: string
            description: ID連携多言語対応有無
          col_name:
            type: string
            description: データベース上のカラム名
          save_type:
            type: string
            description: データベース上の保存形式
          auto_input:
            type: integer
            description: 自動入力フラグ
          input_item:
            type: integer
            description: 入力対象フラグ
          view_item:
            type: string
            description: 出力対象フラグ
          unique_item:
            type: integer
            description: 必須入力フラグ
          required_item:
            type: integer
            description: 一意制約フラグ
          initial_value:
            type: string
            description: 入力欄初期値
          validate_option:
            type: object
            description: バリデーション値
          before_validate_register:
            type: object
            description: 個別バリデーション(前)
          after_validate_register:
            type: object
            description: 個別バリデーション(後)
        example:
          initial_value: initial_value
          column_disp_seq: 6
          required_item: 2
          ref_table_name: ref_table_name
          save_type: save_type
          column_name: column_name
          unique_item: 5
          description: description
          input_item: 5
          before_validate_register: {}
          col_name: col_name
          column_name_rest: column_name_rest
          column_id: column_id
          ref_multi_lang: ref_multi_lang
          validate_option: {}
          ref_pkey_name: ref_pkey_name
          auto_input: 1
          view_item: view_item
          ref_col_name: ref_col_name
          column_group_id: column_group_id
          after_validate_register: {}
          column_type: 0
          column_group_name: column_group_name
          ref_sort_conditions: ref_sort_conditions
      description: column_name_restがkeyになる
    MENU_INFO:
      type: object
      properties:
        menu_info:
          type: string
          description: メニューの説明
        menu_group_id:
          type: string
          description: メニューグループID
        menu_group_name:
          type: string
          description: メニューグループの名称
        menu_id:
          type: string
          description: メニューID
        menu_name:
          type: string
          description: メニューの名称
        sheet_type:
          type: string
          description: シートタイプ
        history_table_flag:
          type: string
          description: 履歴テーブル有無
        table_name:
          type: string
          description: テーブル名
        view_name:
          type: string
          description: ビュー名
        inherit:
          type: boolean
          description: 継承フラグ
        vertical:
          type: boolean
          description: 縦型フラグ
        login_necessity:
          type: boolean
          description: 認証有無
        auto_filter_flg:
          type: boolean
          description: オートフィルタフラグ
        initial_filter_flg:
          type: boolean
          description: 初回フィルタフラグ
        web_print_limit:
          type: integer
          description: Web表示最大行数
        web_print_confirm:
          type: integer
          description: Web表示前確認行数
        xls_print_limit:
          type: integer
          description: Excel出力最大行数
        sort_key:
          type: string
          description: ソートキー
      example:
        sheet_type: sheet_type
        history_table_flag: history_table_flag
        web_print_limit: 7
        initial_filter_flg: true
        vertical: true
        sort_key: sort_key
        table_name: table_name
        menu_group_id: menu_group_id
        xls_print_limit: 3
        menu_info: menu_info
        menu_name: menu_name
        inherit: true
        menu_group_name: menu_group_name
        auto_filter_flg: true
        menu_id: menu_id
        view_name: view_name
        login_necessity: true
        web_print_confirm: 9
    ERROR_TEMPLATE:
      type: object
      properties:
        result:
          type: string
          example: 001-002
        message:
          type: string
    MAINTENANCE_PARAMETER_P:
      type: object
      properties:
        rest_key_name:
          type: string
    MAINTENANCE_PARAMETER_F:
      type: object
      properties:
        rest_key_name:
          type: string
          example: base64 encode file
    MAINTENANCE_PARAMETERS:
      type: object
      properties:
        parameter:
          $ref: '#/components/schemas/MAINTENANCE_PARAMETERS_parameter'
        file:
          $ref: '#/components/schemas/MAINTENANCE_PARAMETERS_file'
        type:
          type: string
          example: Register/Update
    inline_response_200:
      type: object
      properties:
        result:
          type: string
          example: 001-002
        data:
          $ref: '#/components/schemas/inline_response_200_data'
        message:
          type: string
      example:
        result: 001-002
        data:
          menu_info:
            sheet_type: sheet_type
            history_table_flag: history_table_flag
            web_print_limit: 7
            initial_filter_flg: true
            vertical: true
            sort_key: sort_key
            table_name: table_name
            menu_group_id: menu_group_id
            xls_print_limit: 3
            menu_info: menu_info
            menu_name: menu_name
            inherit: true
            menu_group_name: menu_group_name
            auto_filter_flg: true
            menu_id: menu_id
            view_name: view_name
            login_necessity: true
            web_print_confirm: 9
          column_info:
            key:
              initial_value: initial_value
              column_disp_seq: 6
              required_item: 2
              ref_table_name: ref_table_name
              save_type: save_type
              column_name: column_name
              unique_item: 5
              description: description
              input_item: 5
              before_validate_register: {}
              col_name: col_name
              column_name_rest: column_name_rest
              column_id: column_id
              ref_multi_lang: ref_multi_lang
              validate_option: {}
              ref_pkey_name: ref_pkey_name
              auto_input: 1
              view_item: view_item
              ref_col_name: ref_col_name
              column_group_id: column_group_id
              after_validate_register: {}
              column_type: 0
              column_group_name: column_group_name
              ref_sort_conditions: ref_sort_conditions
        message: message
    inline_response_200_1:
      type: object
      properties:
        result:
          type: string
          example: 001-002
        data:
          type: array
          example:
          - column1
          - column2
          - column3
          items: {}
        message:
          type: string
      example:
        result: 001-002
        data:
        - column1
        - column2
        - column3
        message: message
    inline_response_200_2:
      type: object
      properties:
        result:
          type: string
          example: 001-002
        data:
          type: array
          example:
            id1: name1
            id2: name2
            id3: name3
          items: {}
        message:
          type: string
      example:
        result: 001-002
        data:
          id1: name1
          id2: name2
          id3: name3
        message: message
    inline_response_200_3:
      type: object
      properties:
        TABLE:
          $ref: '#/components/schemas/TABLE'
      example:
        TABLE:
          TD: {}
          TD_IHP: {}
          PAGE_NO: 0
          UNIQUE_VAL: {}
    inline_response_200_4:
      type: object
      properties:
        status:
          type: string
      example:
        status: status
    menu_maintenance_body:
      properties:
        parameter:
          $ref: '#/components/schemas/MAINTENANCE_PARAMETER_P'
        file:
          $ref: '#/components/schemas/MAINTENANCE_PARAMETER_F'
      description: 登録する値を設定
    inline_response_200_5:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          $ref: '#/components/schemas/inline_response_200_5_data'
        message:
          type: string
          example: SUCCESS
      example:
        result: 000-00000
        data:
          user_id: id-xxxxxxxx
          user_name: User Name
          roles:
          - role1
          - role2
          - role3
          workspaces:
          - workspace1
          - workspace2
          - workspace3
        message: SUCCESS
    inline_response_200_6:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          $ref: '#/components/schemas/inline_response_200_6_data'
        message:
          type: string
          example: SUCCESS
      example:
        result: 000-00000
        data:
          menu_groups:
          - disp_seq: 10
            id: "101"
            menu_group_name: メニューグループ1
            menus:
            - disp_seq: 10
              id: "10101"
              menu_name: メニュー1
              menu_name_rest: menu_1
            - disp_seq: 20
              id: "10102"
              menu_name: メニュー2
              menu_name_rest: menu_2
            - disp_seq: 30
              id: "10103"
              menu_name: メニュー3
              menu_name_rest: menu_3
          - disp_seq: 20
            id: "102"
            menu_group_name: メニューグループ2
            menus:
            - disp_seq: 10
              id: "10104"
              menu_name: メニュー4
              menu_name_rest: menu_4
            - disp_seq: 20
              id: "10105"
              menu_name: メニュー5
              menu_name_rest: menu_5
            - disp_seq: 30
              id: "10106"
              menu_name: メニュー6
              menu_name_rest: menu_6
          - disp_seq: 30
            id: "103"
            menu_group_name: メニューグループ3
            menus:
            - disp_seq: 10
              id: "10107"
              menu_name: メニュー7
              menu_name_rest: menu_7
            - disp_seq: 20
              id: "10108"
              menu_name: メニュー8
              menu_name_rest: menu_8
            - disp_seq: 30
              id: "10109"
              menu_name: メニュー9
              menu_name_rest: menu_9
        message: SUCCESS
    inline_response_200_7:
      type: object
      properties:
        result:
          type: string
          example: 000-00000
        data:
          type: object
          additionalProperties:
            type: string
            properties:
              panelFileEncoded:
                description: メニューグループの画像ファイルをbase64エンコードした値
          description: メニューグループIDがkeyになる
        message:
          type: string
          example: SUCCESS
      example:
        result: 000-00000
        data:
          key: data
        message: SUCCESS
    MAINTENANCE_PARAMETERS_parameter:
      type: object
      properties:
        rest_key_name:
          type: string
      example: null
    MAINTENANCE_PARAMETERS_file:
      type: object
      properties:
        rest_key_name:
          type: string
          example: base64 encode file
      example: null
    inline_response_200_data:
      type: object
      properties:
        column_info:
          $ref: '#/components/schemas/COLUMN_INFO'
        menu_info:
          $ref: '#/components/schemas/MENU_INFO'
      example:
        menu_info:
          sheet_type: sheet_type
          history_table_flag: history_table_flag
          web_print_limit: 7
          initial_filter_flg: true
          vertical: true
          sort_key: sort_key
          table_name: table_name
          menu_group_id: menu_group_id
          xls_print_limit: 3
          menu_info: menu_info
          menu_name: menu_name
          inherit: true
          menu_group_name: menu_group_name
          auto_filter_flg: true
          menu_id: menu_id
          view_name: view_name
          login_necessity: true
          web_print_confirm: 9
        column_info:
          key:
            initial_value: initial_value
            column_disp_seq: 6
            required_item: 2
            ref_table_name: ref_table_name
            save_type: save_type
            column_name: column_name
            unique_item: 5
            description: description
            input_item: 5
            before_validate_register: {}
            col_name: col_name
            column_name_rest: column_name_rest
            column_id: column_id
            ref_multi_lang: ref_multi_lang
            validate_option: {}
            ref_pkey_name: ref_pkey_name
            auto_input: 1
            view_item: view_item
            ref_col_name: ref_col_name
            column_group_id: column_group_id
            after_validate_register: {}
            column_type: 0
            column_group_name: column_group_name
            ref_sort_conditions: ref_sort_conditions
    inline_response_200_5_data:
      type: object
      properties:
        roles:
          example:
          - role1
          - role2
          - role3
        user_id:
          example: id-xxxxxxxx
        user_name:
          example: User Name
        workspaces:
          example:
          - workspace1
          - workspace2
          - workspace3
      example:
        user_id: id-xxxxxxxx
        user_name: User Name
        roles:
        - role1
        - role2
        - role3
        workspaces:
        - workspace1
        - workspace2
        - workspace3
    inline_response_200_6_data:
      type: object
      properties:
        menu_groups:
          example:
          - disp_seq: 10
            id: "101"
            menu_group_name: メニューグループ1
            menus:
            - disp_seq: 10
              id: "10101"
              menu_name: メニュー1
              menu_name_rest: menu_1
            - disp_seq: 20
              id: "10102"
              menu_name: メニュー2
              menu_name_rest: menu_2
            - disp_seq: 30
              id: "10103"
              menu_name: メニュー3
              menu_name_rest: menu_3
          - disp_seq: 20
            id: "102"
            menu_group_name: メニューグループ2
            menus:
            - disp_seq: 10
              id: "10104"
              menu_name: メニュー4
              menu_name_rest: menu_4
            - disp_seq: 20
              id: "10105"
              menu_name: メニュー5
              menu_name_rest: menu_5
            - disp_seq: 30
              id: "10106"
              menu_name: メニュー6
              menu_name_rest: menu_6
          - disp_seq: 30
            id: "103"
            menu_group_name: メニューグループ3
            menus:
            - disp_seq: 10
              id: "10107"
              menu_name: メニュー7
              menu_name_rest: menu_7
            - disp_seq: 20
              id: "10108"
              menu_name: メニュー8
              menu_name_rest: menu_8
            - disp_seq: 30
              id: "10109"
              menu_name: メニュー9
              menu_name_rest: menu_9
      example:
        menu_groups:
        - disp_seq: 10
          id: "101"
          menu_group_name: メニューグループ1
          menus:
          - disp_seq: 10
            id: "10101"
            menu_name: メニュー1
            menu_name_rest: menu_1
          - disp_seq: 20
            id: "10102"
            menu_name: メニュー2
            menu_name_rest: menu_2
          - disp_seq: 30
            id: "10103"
            menu_name: メニュー3
            menu_name_rest: menu_3
        - disp_seq: 20
          id: "102"
          menu_group_name: メニューグループ2
          menus:
          - disp_seq: 10
            id: "10104"
            menu_name: メニュー4
            menu_name_rest: menu_4
          - disp_seq: 20
            id: "10105"
            menu_name: メニュー5
            menu_name_rest: menu_5
          - disp_seq: 30
            id: "10106"
            menu_name: メニュー6
            menu_name_rest: menu_6
        - disp_seq: 30
          id: "103"
          menu_group_name: メニューグループ3
          menus:
          - disp_seq: 10
            id: "10107"
            menu_name: メニュー7
            menu_name_rest: menu_7
          - disp_seq: 20
            id: "10108"
            menu_name: メニュー8
            menu_name_rest: menu_8
          - disp_seq: 30
            id: "10109"
            menu_name: メニュー9
            menu_name_rest: menu_9

